import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Wrapper from "./component/shared/Wrapper";
import Footer from './component/view/Footer'
const robotSerif = Roboto_Serif({
  variable: "--font-robot-serif",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotSerif.variable}  antialiased`}
      >
        <Wrapper>
        {children}
        </Wrapper>
        <Footer />
      </body>
    </html>
  );
}
